USE v_db;
DESC users;
DROP TABLE users;

CREATE TABLE users (
  id INT PRIMARY KEY AUTO_INCREMENT COMMENT '使用者ID',
  name VARCHAR(100) NOT NULL COMMENT '使用者姓名',
  account VARCHAR(100) NOT NULL UNIQUE COMMENT '帳號(使用信箱)',
  password VARCHAR(100) NOT NULL COMMENT '密碼（要加密）',
  email VARCHAR(100) COMMENT '聯絡或驗證信箱',
  phone VARCHAR(20) COMMENT '手機號碼',
  birthday DATE COMMENT '會員生日',
  gender VARCHAR(10) COMMENT '性別',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '註冊日期',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '資料更新日期',
  is_valid TINYINT NOT NULL DEFAULT 1
);